[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn edupos.wsgi --log-file -"
healthcheckPath = "/login/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
