# Generated by Django 6.0.3 on 2026-04-10 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_alter_movimientoinventario_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('desechables', 'Desechables'), ('limpieza', 'Limpieza'), ('empaque', 'Empaque'), ('utensilio', 'Utensilio'), ('otro', 'Otro')], default='otro', max_length=15)),
                ('unidad', models.CharField(choices=[('und', 'Unidades'), ('paquete', 'Paquetes'), ('caja', 'Cajas'), ('rollo', 'Rollos'), ('kg', 'Kilogramos'), ('l', 'Litros')], default='und', max_length=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='insumos/')),
                ('descripcion', models.TextField(blank=True)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=4, default=0, help_text='Precio de referencia por unidad', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos', to='app_admin.proveedor')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Consumo'), ('ajuste', 'Ajuste manual'), ('merma', 'Merma / Pérdida')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='app_admin.insumo')),
            ],
            options={
                'verbose_name': 'Movimiento de Insumo',
                'verbose_name_plural': 'Movimientos de Insumos',
                'ordering': ['-fecha'],
            },
        ),
    ]
