# Generated by Django 6.0.3 on 2026-04-20 05:59

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_insumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ingredientes/', validators=[authentication.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='insumos/', validators=[authentication.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='perfiladmin',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', validators=[authentication.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', validators=[authentication.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='proveedores/', validators=[authentication.validators.validate_image]),
        ),
    ]
