# Generated by Django 6.0.3 on 2026-04-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0005_alter_ingrediente_imagen_alter_insumo_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('gluten', 'Gluten'), ('lacteos', 'Lácteos'), ('huevo', 'Huevo'), ('mani', 'Maní / Cacahuate'), ('soya', 'Soya'), ('nueces', 'Frutos secos'), ('mariscos', 'Mariscos / Crustáceos'), ('pescado', 'Pescado'), ('mostaza', 'Mostaza'), ('apio', 'Apio'), ('sesamo', 'Sésamo'), ('sulfitos', 'Sulfitos'), ('moluscos', 'Moluscos'), ('otro', 'Otro')], max_length=20, unique=True)),
                ('icono', models.CharField(blank=True, help_text='Emoji o clase Bootstrap Icon', max_length=10)),
            ],
            options={
                'verbose_name': 'Alérgeno',
                'verbose_name_plural': 'Alérgenos',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='porcentaje_merma',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% de pérdida esperada en preparación (ej: 5.00 = 5%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='stock_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alerta de sobrestock si se supera este valor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='alergenos',
            field=models.ManyToManyField(blank=True, related_name='ingredientes', to='app_admin.alergeno', verbose_name='Alérgenos que contiene'),
        ),
    ]
