# Generated by Django 6.0.3 on 2026-04-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0010_lote_produccion_ingrediente_v3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Alerta cuando stock_real baje de este valor (en unidades base)', max_digits=10),
        ),
    ]
