# Generated by Django 6.0.3 on 2026-05-20 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0011_alter_ingrediente_stock_minimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('gcal_id', models.CharField(default='primary', help_text='ID del calendario de Google (se asigna automáticamente)', max_length=300)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gcal', to='app_admin.perfiladmin')),
            ],
            options={
                'verbose_name': 'Token Google Calendar',
                'verbose_name_plural': 'Tokens Google Calendar',
            },
        ),
    ]
