# Generated by Django 6.0.3 on 2026-06-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0012_google_calendar_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icono',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
