# Generated by Django 6.0.3 on 2026-04-17 05:04

import authentication.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_docente', '0002_recargadocente'),
        ('authentication', '0004_docente_limite_fiado_default_zero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recargadocente',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='recargas/docentes/', validators=[authentication.validators.validate_image]),
        ),
        migrations.CreateModel(
            name='MovimientoFiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cargo', 'Cargo (pedido)'), ('abono', 'Abono (pago)'), ('ajuste', 'Ajuste manual')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_post', models.DecimalField(decimal_places=2, help_text='Deuda total del docente después del movimiento', max_digits=10)),
                ('nota', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_fiado', to='authentication.docente')),
                ('referencia', models.ForeignKey(blank=True, help_text='Pedido que originó el cargo (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_fiado', to='app_docente.pedidodocente')),
            ],
            options={
                'verbose_name': 'Movimiento de Fiado',
                'verbose_name_plural': 'Movimientos de Fiado',
                'ordering': ['-fecha'],
            },
        ),
    ]
