# Generated by Django 6.0.3 on 2026-04-05 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecargaSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to='authentication.estudiante')),
                ('padre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recargas_realizadas', to='authentication.padre')),
            ],
            options={
                'verbose_name': 'Recarga de Saldo',
                'verbose_name_plural': 'Recargas de Saldo',
                'ordering': ['-fecha'],
            },
        ),
    ]
