# Generated by Django 6.0.3 on 2026-04-06 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_alter_movimientoinventario_cantidad'),
        ('app_padre', '0001_initial'),
        ('authentication', '0002_padre_saldo_and_panel_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recargasaldo',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='recargas/comprobantes/'),
        ),
        migrations.AddField(
            model_name='recargasaldo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15),
        ),
        migrations.AddField(
            model_name='recargasaldo',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recargasaldo',
            name='nota_admin',
            field=models.CharField(blank=True, max_length=300, verbose_name='Nota del administrador'),
        ),
        migrations.AlterField(
            model_name='recargasaldo',
            name='nota',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='HorarioCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Recreo', max_length=80)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='authentication.estudiante')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='authentication.padre')),
            ],
            options={
                'verbose_name': 'Horario de Compra',
                'verbose_name_plural': 'Horarios de Compra',
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recarga_aprobada', 'Recarga Aprobada'), ('recarga_rechazada', 'Recarga Rechazada'), ('recarga_pendiente', 'Recarga Pendiente'), ('limite_cerca', 'Límite Cerca'), ('limite_superado', 'Límite Superado'), ('compra_realizada', 'Compra Realizada'), ('compra_bloqueada', 'Compra Bloqueada'), ('pedido_padre', 'Pedido del Padre'), ('saldo_bajo', 'Saldo Bajo'), ('info', 'Información')], default='info', max_length=25)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('url_accion', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='authentication.padre')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PedidoPadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(choices=[('saldo_hijo', 'Saldo del hijo'), ('saldo_padre', 'Saldo del padre')], default='saldo_hijo', max_length=15)),
                ('nota', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_realizados', to='authentication.padre')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_padre', to='app_admin.pedido')),
            ],
            options={
                'verbose_name': 'Pedido del Padre',
                'verbose_name_plural': 'Pedidos del Padre',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PedidoProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('hora_entrega', models.TimeField(blank=True, null=True)),
                ('fuente', models.CharField(choices=[('saldo_hijo', 'Saldo del hijo'), ('saldo_padre', 'Saldo del padre')], default='saldo_hijo', max_length=15)),
                ('nota', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('procesado', 'Procesado'), ('cancelado', 'Cancelado')], default='activo', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_programados', to='authentication.estudiante')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_programados', to='authentication.padre')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programados', to='app_admin.pedido')),
            ],
            options={
                'verbose_name': 'Pedido Programado',
                'verbose_name_plural': 'Pedidos Programados',
                'ordering': ['fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='DetalleProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_admin.producto')),
                ('pedido_prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_padre.pedidoprogramado')),
            ],
            options={
                'verbose_name': 'Detalle Pedido Programado',
                'verbose_name_plural': 'Detalles Pedidos Programados',
            },
        ),
        migrations.CreateModel(
            name='RestriccionAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restricciones', to='app_admin.categoria')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restricciones', to='authentication.estudiante')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricciones', to='authentication.padre')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restricciones', to='app_admin.producto')),
            ],
            options={
                'verbose_name': 'Restricción Alimenticia',
                'verbose_name_plural': 'Restricciones Alimenticias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LimiteGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites', to='authentication.estudiante')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites', to='authentication.padre')),
            ],
            options={
                'verbose_name': 'Límite de Gasto',
                'verbose_name_plural': 'Límites de Gasto',
                'unique_together': {('padre', 'estudiante', 'tipo')},
            },
        ),
    ]
