# Generated by Django 6.0.3 on 2026-04-10 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_padre', '0002_padre_saldo_and_panel_completo'),
        ('authentication', '0002_padre_saldo_and_panel_completo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlergiaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Maní, Lactosa, Gluten, Mariscos…', max_length=100)),
                ('tipo', models.CharField(choices=[('alergia', 'Alergia'), ('intolerancia', 'Intolerancia'), ('sensibilidad', 'Sensibilidad')], default='alergia', max_length=15)),
                ('gravedad', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('severa', 'Severa / Anafilaxia')], default='leve', max_length=12)),
                ('notas', models.TextField(blank=True, help_text='Síntomas, medicación, instrucciones de emergencia…')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alergias', to='authentication.estudiante')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alergias', to='authentication.padre')),
            ],
            options={
                'verbose_name': 'Alergia de Estudiante',
                'verbose_name_plural': 'Alergias de Estudiantes',
                'ordering': ['-gravedad', 'nombre'],
            },
        ),
    ]
