# Generated by Django 6.0.3 on 2026-04-17 05:05

import authentication.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_padre', '0003_alergia_estudiante'),
        ('authentication', '0005_historicaldocente_historicalestudiante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recargasaldo',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='recargas/comprobantes/', validators=[authentication.validators.validate_image]),
        ),
        migrations.CreateModel(
            name='HistoricalRecargaSaldo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprobante', models.TextField(blank=True, max_length=100, null=True, validators=[authentication.validators.validate_image])),
                ('nota', models.CharField(blank=True, max_length=300)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15)),
                ('nota_admin', models.CharField(blank=True, max_length=300, verbose_name='Nota del administrador')),
                ('fecha', models.DateTimeField(blank=True, editable=False)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('estudiante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentication.estudiante')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('padre', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentication.padre')),
            ],
            options={
                'verbose_name': 'historical Recarga de Saldo',
                'verbose_name_plural': 'historical Recargas de Saldo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
