# Generated by Django 6.0.3 on 2026-04-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_padre', '0004_alter_recargasaldo_comprobante_and_more'),
        ('authentication', '0006_sede_alter_perfil_rol_historicalempleado_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleprogramado',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio congelado al momento de programar el pedido', max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='alergiaestudiante',
            unique_together={('estudiante', 'nombre', 'tipo')},
        ),
    ]
