# Generated by Django 6.0.3 on 2026-04-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_padre', '0006_recargapadre'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrecargasaldo',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalrecargasaldo',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recargapadre',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recargapadre',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recargasaldo',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recargasaldo',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
