# Generated by Django 6.0.3 on 2026-04-29 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0011_alter_ingrediente_stock_minimo'),
        ('app_padre', '0007_historicalrecargasaldo_mp_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alergiaestudiante',
            name='alergeno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alergias_estudiante', to='app_admin.alergeno'),
        ),
    ]
