# Generated by Django 6.0.3 on 2026-04-01 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('padre', 'Padre de Familia'), ('estudiante', 'Estudiante')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(blank=True, max_length=20, verbose_name='N° documento')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='padre', to='authentication.perfil')),
            ],
            options={
                'verbose_name': 'Padre de Familia',
                'verbose_name_plural': 'Padres de Familia',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=10)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='authentication.padre')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='authentication.perfil')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
    ]
