# Generated by Django 6.0.3 on 2026-04-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='padre',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo propio'),
        ),
    ]
