# Generated by Django 6.0.3 on 2026-04-20 05:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_historicaldocente_historicalestudiante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('ciudad', models.CharField(default='Cali', max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('padre', 'Padre de Familia'), ('estudiante', 'Estudiante'), ('docente', 'Docente'), ('empleado', 'Empleado')], max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricalEmpleado',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('documento', models.CharField(blank=True, max_length=20, verbose_name='N° Documento')),
                ('cargo', models.CharField(choices=[('cajero', 'Cajero'), ('atencion', 'Atención al Cliente'), ('supervisor', 'Supervisor de Sede')], default='cajero', max_length=20)),
                ('es_global', models.BooleanField(default=False, help_text='Puede visualizar información consolidada de todas las sedes', verbose_name='Acceso global')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('perfil', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentication.perfil')),
            ],
            options={
                'verbose_name': 'historical Empleado',
                'verbose_name_plural': 'historical Empleados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(blank=True, max_length=20, verbose_name='N° Documento')),
                ('cargo', models.CharField(choices=[('cajero', 'Cajero'), ('atencion', 'Atención al Cliente'), ('supervisor', 'Supervisor de Sede')], default='cajero', max_length=20)),
                ('es_global', models.BooleanField(default=False, help_text='Puede visualizar información consolidada de todas las sedes', verbose_name='Acceso global')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to='authentication.perfil')),
                ('sedes', models.ManyToManyField(blank=True, related_name='empleados', to='authentication.sede')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
