# Generated by Django 6.0.3 on 2026-04-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_email_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='puede_recargar_autonomo',
            field=models.BooleanField(default=False, help_text='El padre puede habilitar que el estudiante recargue su saldo directamente con MercadoPago.', verbose_name='Puede recargar autónomamente'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='puede_recargar_autonomo',
            field=models.BooleanField(default=False, help_text='El padre puede habilitar que el estudiante recargue su saldo directamente con MercadoPago.', verbose_name='Puede recargar autónomamente'),
        ),
    ]
