# Generated by Django 6.0.3 on 2026-05-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_docente_fiado'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='huella_enrolada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='huella_template',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='huella_enrolada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='huella_template',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocente',
            name='huella_enrolada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocente',
            name='huella_template',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='huella_enrolada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='huella_template',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
