# Generated by Django 6.0.3 on 2026-04-20 05:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_admin', '0005_alter_ingrediente_imagen_alter_insumo_imagen_and_more'),
        ('authentication', '0006_sede_alter_perfil_rol_historicalempleado_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(editable=False, max_length=20, unique=True)),
                ('tipo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('cuenta_estudiante', 'Cuenta Estudiante'), ('cuenta_docente', 'Cuenta Docente')], default='efectivo', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('nota', models.TextField(blank=True)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_empleado', to='authentication.docente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='authentication.empleado')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_empleado', to='authentication.estudiante')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='authentication.sede')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='app_admin.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_empleado.ventaempleado')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
    ]
