# Generated by Django 6.0.3 on 2026-04-21 21:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empleado', '0001_initial'),
        ('authentication', '0006_sede_alter_perfil_rol_historicalempleado_empleado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaempleado',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ventaempleado',
            name='fiado_usado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto cargado a fiado en ventas de docente', max_digits=10),
        ),
        migrations.CreateModel(
            name='AnulacionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('supervisor_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anulaciones_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anulacion', to='app_empleado.ventaempleado')),
            ],
            options={
                'verbose_name': 'Anulación de Venta',
                'verbose_name_plural': 'Anulaciones de Venta',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TurnoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10)),
                ('apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('cierre', models.DateTimeField(blank=True, null=True)),
                ('efectivo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('efectivo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nota', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='authentication.empleado')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='authentication.sede')),
            ],
            options={
                'verbose_name': 'Turno de Caja',
                'verbose_name_plural': 'Turnos de Caja',
                'ordering': ['-apertura'],
            },
        ),
        migrations.AddField(
            model_name='ventaempleado',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_turno', to='app_empleado.turnocaja'),
        ),
    ]
